# Generated by Django 3.1.4 on 2020-12-13 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20201213_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mobileno',
            new_name='mobilenumber',
        ),
    ]
