# Generated by Django 3.1.4 on 2020-12-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20201213_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobilenumber',
            field=models.IntegerField(),
        ),
    ]
