# Generated by Django 3.1.4 on 2020-12-22 14:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
