# Generated by Django 3.1.4 on 2020-12-23 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_info_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=130),
            preserve_default=False,
        ),
    ]
