# Generated by Django 3.1.4 on 2020-12-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20201223_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='img',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
