# Generated by Django 3.1.4 on 2021-01-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='cont',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='news',
            name='name',
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
