# Generated by Django 3.1.4 on 2021-01-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_news_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img1',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
